server:
  port: 8082

spring:
  config:
    import: "optional:file:./.local/nihongo-gateway.properties,optional:file:../.local/nihongo-gateway.properties,optional:file:./.local/audit-secrets-gateway.properties,optional:file:./gateway/.local/audit-secrets-gateway.properties"
  application:
    name: gateway-service

  data:
    redis:
      host: ${REDIS_HOST:160.22.107.232}
      port: ${REDIS_PORT:6379}
      username: ${REDIS_USERNAME:}
      password: ${REDIS_PASSWORD:thuThuy@123}

  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: true

          routes:
            - id: japanese-ai
              uri: lb://nihongo-user-service
              predicates:
                - Path=/api/nihongo-user/japanese
              filters:
                - name: RequestRateLimiter
                  args:
                    redis-rate-limiter.replenishRate: 1
                    redis-rate-limiter.burstCapacity: 60
                    redis-rate-limiter.requestedTokens: 10

            - id: wallet-websocket
              uri: lb:ws://nihongo-user-service
              predicates:
                - Path=/api/nihongo-user/wallets/ws

            - id: user-service
              uri: lb://user-service
              predicates:
                - Path=/api/auth/**,/api/users/**,/api/active-user/**,/images/**
              filters:
                - name: RequestRateLimiter
                  args:
                    redis-rate-limiter.replenishRate: 10
                    redis-rate-limiter.burstCapacity: 20
                    redis-rate-limiter.requestedTokens: 1

            - id: admin-service
              uri: lb://admin-service
              predicates:
                - Path=/api/admin/**
              filters:
                - name: RequestRateLimiter
                  args:
                    redis-rate-limiter.replenishRate: 10
                    redis-rate-limiter.burstCapacity: 20
                    redis-rate-limiter.requestedTokens: 1

            - id: staff-service
              uri: lb://staff-service
              predicates:
                - Path=/api/staff/**
              filters:
                - name: RequestRateLimiter
                  args:
                    redis-rate-limiter.replenishRate: 10
                    redis-rate-limiter.burstCapacity: 20
                    redis-rate-limiter.requestedTokens: 1

            - id: staff-performance-websocket
              uri: lb:ws://staff-service
              order: -1
              predicates:
                - Path=/api/staff/vps-performance/ws

            - id: nihongo-user-service
              uri: lb://nihongo-user-service
              predicates:
                - Path=/api/nihongo-user/**
              filters:
                - name: RequestRateLimiter
                  args:
                    redis-rate-limiter.replenishRate: 10
                    redis-rate-limiter.burstCapacity: 20
                    redis-rate-limiter.requestedTokens: 1

eureka:
  instance:
    prefer-ip-address: true

  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}
    register-with-eureka: true
    fetch-registry: true

jwt:
  secret: ${JWT_SECRET}
