server:
  port: 8082

spring:
  config:
    import: "optional:file:./.local/shared.properties,optional:file:../.local/shared.properties"
  application:
    name: gateway-service

  cloud:
    gateway:
      server:
        webflux:
          httpclient:
            connect-timeout: 3000
            response-timeout: 15s
          discovery:
            locator:
              enabled: true

          routes:
            - id: japanese-ai
              uri: lb://nihongo-user-service
              metadata:
                response-timeout: 70000
              predicates:
                - Path=/api/nihongo-user/japanese
            - id: wallet-websocket
              uri: lb:ws://nihongo-user-service
              predicates:
                - Path=/api/nihongo-user/wallets/ws

            - id: user-service
              uri: lb://user-service
              predicates:
                - Path=/api/auth/**,/api/users/**,/api/active-user/**,/images/**
            - id: admin-service
              uri: lb://admin-service
              predicates:
                - Path=/api/admin/**
            - id: staff-service
              uri: lb://staff-service
              predicates:
                - Path=/api/staff/**
            - id: staff-performance-websocket
              uri: lb:ws://staff-service
              order: -1
              predicates:
                - Path=/api/staff/vps-performance/ws

            - id: nihongo-user-service
              uri: lb://nihongo-user-service
              predicates:
                - Path=/api/nihongo-user/**
eureka:
  instance:
    prefer-ip-address: true

  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}
    register-with-eureka: true
    fetch-registry: true

jwt:
  secret: ${JWT_SECRET}

auth:
  session-validation-url: ${AUTH_SESSION_VALIDATION_URL:http://127.0.0.1:8081/api/auth/session/validate}
